import logo from "../Assets/images/logo.png"
import pic from "../Assets/images/pic.png"
import pic3 from "../Assets/images/pic3.jpg"
import pic2 from "../Assets/images/pic2.jpg"
import pic1 from "../Assets/images/pic1.jpg"
import pic4 from "../Assets/images/pic4.jpg"
import pic5 from "../Assets/images/pic5.jpg"
import pic7 from "../Assets/images/pic7.jpg"
import pic6 from "../Assets/images/pic6.jpg"
import pic8 from "../Assets/images/pic8.jpg"
import p6 from "../Assets/images/p6.png"
import p5 from "../Assets/images/p5.png"
import p4 from "../Assets/images/p4.png"
import p3 from "../Assets/images/p3.png"
import p2 from "../Assets/images/p2.png"
import p1 from "../Assets/images/p1.png"
import about_img from "../Assets/images/about_img.jpg"
import about_img1 from "../Assets/images/about_img1.jpg"
import about_img3 from "../Assets/images/about_img3.jpg"
import about_img2 from "../Assets/images/about_img2.jpg"
import about_img4 from "../Assets/images/about_img4.jpg"
import about_img5 from "../Assets/images/about_img5.jpg"
import about_img6 from "../Assets/images/about_img6.jpg"
import about_img7 from "../Assets/images/about_img7.jpg"
import trine_img from "../Assets/images/trine_img.jpg"
import tick from "../Assets/images/tick.png"
import tick1 from "../Assets/images/tick1.png"
import price from "../Assets/images/price.jpg"
import c7 from "../Assets/images/c7.jpg"
import c2 from "../Assets/images/c2.jpg"
import c1 from "../Assets/images/c1.jpg"
import c8 from "../Assets/images/c8.jpg"
import c6 from "../Assets/images/c6.jpg"
import c9 from "../Assets/images/c9.jpg"
import c5 from "../Assets/images/c5.jpg"
import c10 from "../Assets/images/c10.jpg"
import c3 from "../Assets/images/c3.jpg"
import c11 from "../Assets/images/c11.jpg"
import c4 from "../Assets/images/c4.jpg"
import c12 from "../Assets/images/c12.jpg"
import class_img from "../Assets/images/class_img.jpg"
import blog_img1 from "../Assets/images/blog_img1.jpg"
import blog_img3 from "../Assets/images/blog_img3.jpg"
import blog_img2 from "../Assets/images/blog_img2.jpg"

export {
    logo, pic, pic1, pic2, pic3, pic4, pic5, pic6, pic7, pic8, p1, p2, p3,
    p4, p5, p6, about_img, about_img1, about_img3, about_img2, about_img4,
    about_img5, about_img6, about_img7, trine_img, tick, price, tick1,
    c1, c2, c3, c4, c5, c6, c7, c8, c9, c10, c11, c12, class_img, blog_img1,
    blog_img3, blog_img2
};